### ISSUE TITLE
Review and move mautic overview page to read the docs

### ISSUE THREAD

**Issue by fakela** [mautic/user-documentation#1]
From the old documentation https://docs.mautic.org/en/overview-of-mautic we have the overview page  

This needs to be moved to the new documentation. It should be proofreaded and changes should be made where necessary.

**Comment by pragatijain** [comment]
@fakela Where is the link to the new documentation? Are there any documents I can reference before revising the content?

**Comment by fakela** [comment]
> @fakela Where is the link to the new documentation? Are there any documents I can reference before revising the content?

Yeah there are contents you can reference, this is the old documentation https://docs.mautic.org/en.
