### ISSUE TITLE
Getting started page

### ISSUE THREAD

**Issue by fakela** [mautic/user-documentation#14]
Review the Getting started page and move to the new docs
https://docs.mautic.org/en/setup/how-to-install-mautic 

- [ ] add screenshots where necessary

- [ ] proofread the documentation

- [ ] make changes where necessary

- [ ] add additional information that would be useful

**Comment by pragatijain** [comment]
Can I own this one?

**Comment by fakela** [comment]
> Can I own this one?

Sure 🎉

**Comment by pragatijain** [comment]
@fakela Progress update. Planning to work on this one this week. Will share more updates mid-week.

**Comment by RCheesley** [comment]
Closing as this one is complete!
