### ISSUE TITLE
Installing from production package

### ISSUE THREAD

**Issue by fakela** [mautic/user-documentation#15]
Review installing from production package page and move to the new doc
https://docs.mautic.org/en/setup/how-to-install-mautic/install-mautic-from-package

- [ ] add screenshots where necessary
- [ ] proofread the documentation
- [ ] make changes where necessary
- [ ] add additional information that would be useful

**Comment by pragatijain** [comment]
Can I own this one?

**Comment by fakela** [comment]
> Can I own this one?

Sure 🎉

**Comment by pragatijain** [comment]
@fakela I am done with this document. Have not been able to test the setup as I don't have access to the resources to complete the setup. Let me know if there is an alternative way to install the production package online ?

**Comment by fakela** [comment]
@pragatijain from this documentation the steps are highlighted here https://docs.mautic.org/en/setup/how-to-install-mautic/install-mautic-from-package.

There is no alternative way to install from package but there are alternatives way to install Mautic which is through Github or composer

**Comment by fakela** [comment]
We are majorly moving the content to the new site. Can you send a PR once you are done doing that

**Comment by pragatijain** [comment]
> https://docs.mautic.org/en/setup/how-to-install-mautic/install-mautic-from-package

Sounds great!  I had referenced it while copy editing the content.

**Comment by pragatijain** [comment]
https://github.com/mautic/mautic-documentation/pull/288 
@fakela

**Comment by pragatijain** [comment]
@fakela Can we close this ticket if the content is published?

**Comment by RCheesley** [comment]
Closing as this one is complete! 🚀
