### ISSUE TITLE
Installing from Github

### ISSUE THREAD

**Issue by fakela** [mautic/user-documentation#16]
Review installing from Github https://docs.mautic.org/en/setup/how-to-install-mautic/install-mautic-from-github and move to the new documentation

- [ ] add screenshots where necessary

 

- [ ] proofread the documentation

 

- [ ] make changes where necessary

 

- [ ] add additional information that would be useful

**Comment by pragatijain** [comment]
@fakela I think I can own this as I started exploring this section while working on the contributing guidelines page.

**Comment by fakela** [comment]
@pragatijain that will be awesome

**Comment by pragatijain** [comment]
> https://docs.mautic.org/en/setup/how-to-install-mautic/install-mautic-from-github

@fakela can you assign it to me? It is easy for me to track my work.

**Comment by pragatijain** [comment]
[Submitted PR](https://github.com/mautic/user-documentation/pull/25) : https://github.com/mautic/user-documentation/pull/25 

Using [this](https://kb.mautic.org/knowledgebase/development/how-to-install-mautic-using-ddev#further-useful-ddev-tips-and-tricks) Mautic KB article, I reviewed the original page for relevance and accuracy.

**Comment by RCheesley** [comment]
Closing as this one is complete! 🚀
