### ISSUE TITLE
Update readthedocs.yml to use build.os

### ISSUE THREAD

**Issue by RCheesley** [mautic/user-documentation#199]
According to the blog post here: https://blog.readthedocs.com/use-build-os-config/ and the docs here: https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os we need to switch to using build.os.

Small change needed, see https://blog.readthedocs.com/use-build-os-config/ for the details.

**Comment by nox1134** [comment]
Hi @RCheesley! We are already using the build.os config key (https://github.com/mautic/user-documentation/blob/5.x/.readthedocs.yaml). 
Not sure what we have to change here?

**Comment by RCheesley** [comment]
Yes, sorry this was resolved but the issue wasn't closed. Thanks for flagging it up!
