### ISSUE TITLE
Updating at Command line

### ISSUE THREAD

**Issue by fakela** [mautic/user-documentation#21]
https://docs.mautic.org/en/setup/how-to-update-mautic/updating-at-command-line

**Comment by pragatijain** [comment]
@fakela I would like to own this one.

**Comment by fakela** [comment]
@pragatijain it's assigned to you.

**Comment by pragatijain** [comment]
https://github.com/mautic/user-documentation/pull/28

**Comment by RCheesley** [comment]
Closing as this one has been merged
