### ISSUE TITLE
Move tracking script from within Cron Jobs

### ISSUE THREAD

**Issue by RCheesley** [mautic/user-documentation#224]
Not sure how, but the tracking script instructions seem to have been added on the cron jobs page which seems a bit counterintuitive.

https://docs.mautic/org/en/5.x/configuration/cron_jobs.html#tracking-script

I think this should be under the installing Mautic section, perhaps?

NOTE: Update redirect when this is done.

**Comment by nox1134** [comment]
After this PR is merged, we need to set up a redirect on Read the Docs
From URL: `/docs/build/html/configuration/cron_jobs.html#tracking-script`
To URL: `/docs/build/html/configuration/tracking_script.html`
Thanks!
