### ISSUE TITLE
Add progressive profiling section

### ISSUE THREAD

**Issue by RCheesley** [mautic/user-documentation#230]
We seem to be missing this section:

https://github.com/mautic/mautic-documentation/blob/main/pages/11.Components/03.Forms/02.Progressive%20Profiling/docs.en.md

Note: URL for redirecting: https://docs.mautic.org/en/components/forms/progressive-profiling

**Comment by nox1134** [comment]
Hi @RCheesley! Could you please review PR #257?
Thank you!
