### ISSUE TITLE
Add theme structure content

### ISSUE THREAD

**Issue by RCheesley** [mautic/user-documentation#231]
https://docs.mautic.org/en/5.x/themes/theme_structure.html is missing content.

https://github.com/mautic/mautic-documentation/blob/main/pages/21.Themes/03.Theme%20structure/docs.en.md

NOTE: link to https://devdocs.mautic.org :)

**Comment by favour-chibueze** [comment]
Are we to link it to the new [developers](https://devdocs.mautic.org/en/5.x/themes/getting_started.html) doc or write it's own content ? @RCheesley

**Comment by RCheesley** [comment]
Hey there!

Good question! I think I saw just the one line and thought it was missing content. Should be OK to leave as it is, we don't want to confuse folks!
