### ISSUE TITLE
Typo on Version 5 Composer Install Command

### ISSUE THREAD

**Issue by J-Wick4** [mautic/user-documentation#232]
I am assuming

`composer create-project mautic/recommended-project:^4 some-dir --no-interaction
`

Should be

`composer create-project mautic/recommended-project:^5 some-dir --no-interaction
`

URL: [https://docs.mautic.org/en/5.x/getting_started/how_to_install_mautic.html#installing-with-composer](https://docs.mautic.org/en/5.x/getting_started/how_to_install_mautic.html#installing-with-composer)

**Comment by RCheesley** [comment]
@all-contributors please add @J-Wick4 for bugs

Resolved with #233 so closing this issue, thanks @J-Wick4
