### ISSUE TITLE
'Creating Themes' Docs is inaccurate about mjml email theme styling

### ISSUE THREAD

**Issue by markusVJH** [mautic/user-documentation#247]
[The official documentation for creating themes](https://docs.mautic.org/en/5.x/builders/creating_themes.html) says that "At present, Mautic won’t process the mj-head tags. None of the mj-attribuites run, so you have to do all styling inline."

But it turns out, [as discussed in the forums](https://forum.mautic.org/t/are-mj-attributes-functional-on-grapesjs-mjml/21875/5), that mj-style tags inside mj-head tags do indeed work. As a new Mautic user who followed the documentation, it would've saved some time to have known that mj-style tags can be used from the start.

The docs should mention that mj-style tags can be used for styling. At present the mj-style tags are not mentioned.

```

<mj-head>
	<mj-style>
Styling here
	</mj-style>
  </mj-head>
<mj-body>

**Comment by RCheesley** [comment]
Thanks for flagging this up - would be awesome if you could make an update to the docs, would you be up for that?

**Comment by markusVJH** [comment]
Yes, absolutely

**Comment by markusVJH** [comment]
I will work at this later today, will test the other head components also
