### ISSUE TITLE
Ability to sign in via Google

### ISSUE THREAD

**Issue by finleykjames** [mautic/user-documentation#253]
Google changed the way it allows sign-ins to 3rd party apps. Unfortunately, this means that I can't set up  my SMTP because I can't sign into my Google account (through which my business email runs). Is there a way of changing it so that there's an ability to sign in via Google, instead of having to input usernames and passwords?

**Comment by RCheesley** [comment]
Hi there, this repository refers to the Documentation, I think perhaps you're talking about logging into your SMTP provider via the Mautic settings? If so, you should raise this as a feature request at https://forum.mautic.org/c/ideas.

However, Google isn't recommended as an email provider as there are many restrictions which make it unworkable beyond small volume sendings. You may want to consider a different ESP for this reason.
