### ISSUE TITLE
Write documentation on Mailchimp plugin

### ISSUE THREAD

**Issue by fakela** [mautic/user-documentation#328]
We need to write documentation on the Mailchimp plugin
https://docs.mautic.org/en/5.x/plugins/mailchimp.html

old documentation can be found here:
https://github.com/mautic/mautic-documentation/tree/main/pages/15.Plugins/10.Mailchimp

**Comment by CBID2** [comment]
Hey @RCheesley. Can I work on this issue instead of [this one](https://github.com/mautic/hacktoberfest-no-code/issues/3)? I find that my skills line more with it.

**Comment by fakela** [comment]
Okay, if you feel this one feels more inline with your skills. I'll assign it to you

**Comment by fakela** [comment]
> Okay, if you feel this one feels more inline with your skills. I'll assign it to you

@CBID2 you have been assigned. If you have any questions or need guidance don't hesitate to ask

**Comment by CBID2** [comment]
> > Okay, if you feel this one feels more inline with your skills. I'll assign it to you
> 
> [@CBID2](https://github.com/CBID2) you have been assigned. If you have any questions or need guidance don't hesitate to ask

Whoa that's a quick response lol! 😄 Thanks @fakela! 😄
